site_name: My Docs
# theme: ivory   #pip3 install mkdocs-windmill
# theme: windmill   #pip3 install mkdocs-windmill
# sudo pip3 install mkdocs-gitbook
# theme:
#   name: gitbook
theme:
  name: windmill
