site_name: Java基础知识
# theme: ivory   #pip3 install mkdocs-windmill
# theme: windmill   #pip3 install mkdocs-windmill
# sudo pip3 install mkdocs-gitbook
# theme:
#   name: gitbook
theme:
  name: windmill
nav:
  - map遍历: map-foreach.md
  - regex表达式: regex.md
